## Importing the dependencies

In [1]:
import os
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
np.expand_dims??

## Loading the data

In [3]:
df = pd.read_csv('train.csv')

In [4]:
df.shape

(159571, 8)

In [5]:
df.head()

id                                       comment_text  toxic  \
0  0000997932d777bf  Explanation\nWhy the edits made under my usern...      0   
1  000103f0d9cfb60f  D'aww! He matches this background colour I'm s...      0   
2  000113f07ec002fd  Hey man, I'm really not trying to edit war. It...      0   
3  0001b41b1c6bb37e  "\nMore\nI can't make any real suggestions on ...      0   
4  0001d958c54c6e35  You, sir, are my hero. Any chance you remember...      0   

   severe_toxic  obscene  threat  insult  identity_hate  
0             0        0       0       0              0  
1             0        0       0       0              0  
2             0        0       0       0              0  
3             0        0       0       0              0  
4             0        0       0       0              0

In [6]:
df.tail()

id                                       comment_text  \
159566  ffe987279560d7ff  ":::::And for the second time of asking, when ...   
159567  ffea4adeee384e90  You should be ashamed of yourself \n\nThat is ...   
159568  ffee36eab5c267c9  Spitzer \n\nUmm, theres no actual article for ...   
159569  fff125370e4aaaf3  And it looks like it was actually you who put ...   
159570  fff46fc426af1f9a  "\nAnd ... I really don't think you understand...   

        toxic  severe_toxic  obscene  threat  insult  identity_hate  
159566      0             0        0       0       0              0  
159567      0             0        0       0       0              0  
159568      0             0        0       0       0              0  
159569      0             0        0       0       0              0  
159570      0             0        0       0       0              0

In [7]:
df.iloc[0]['comment_text']

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [8]:
df[df.columns[2:]].iloc[0]

toxic            0
severe_toxic     0
obscene          0
threat           0
insult           0
identity_hate    0
Name: 0, dtype: int64

## Preprocessing the data

In [9]:
from tensorflow.keras.layers import TextVectorization

In [10]:
TextVectorization??

In [11]:
X = df['comment_text']
y = df[df.columns[2:]].values

In [12]:
X

0         Explanation\nWhy the edits made under my usern...
1         D'aww! He matches this background colour I'm s...
2         Hey man, I'm really not trying to edit war. It...
3         "\nMore\nI can't make any real suggestions on ...
4         You, sir, are my hero. Any chance you remember...
                                ...                        
159566    ":::::And for the second time of asking, when ...
159567    You should be ashamed of yourself \n\nThat is ...
159568    Spitzer \n\nUmm, theres no actual article for ...
159569    And it looks like it was actually you who put ...
159570    "\nAnd ... I really don't think you understand...
Name: comment_text, Length: 159571, dtype: object

In [13]:
y

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int64)

In [14]:
MAX_FEATURES = 200000 # number of words in the vocab

In [15]:
vectorizer = TextVectorization(max_tokens=MAX_FEATURES,
                              output_sequence_length=1800,
                              output_mode='int')

In [16]:
type(X)

pandas.core.series.Series

In [17]:
type(X.values)

numpy.ndarray

In [18]:
vectorizer.adapt(X.values)

In [19]:
vectorizer.get_vocabulary()

['',
 '[UNK]',
 'the',
 'to',
 'of',
 'and',
 'a',
 'you',
 'i',
 'is',
 'that',
 'in',
 'it',
 'for',
 'this',
 'not',
 'on',
 'be',
 'as',
 'have',
 'are',
 'your',
 'with',
 'if',
 'article',
 'was',
 'or',
 'but',
 'page',
 'my',
 'an',
 'from',
 'by',
 'do',
 'at',
 'about',
 'me',
 'so',
 'wikipedia',
 'can',
 'what',
 'there',
 'all',
 'has',
 'will',
 'talk',
 'please',
 'would',
 'its',
 'no',
 'one',
 'just',
 'like',
 'they',
 'he',
 'dont',
 'which',
 'any',
 'been',
 'should',
 'more',
 'we',
 'some',
 'other',
 'who',
 'see',
 'here',
 'also',
 'his',
 'think',
 'im',
 'because',
 'know',
 'how',
 'am',
 'people',
 'why',
 'edit',
 'articles',
 'only',
 'out',
 'up',
 'when',
 'were',
 'use',
 'then',
 'may',
 'time',
 'did',
 'them',
 'now',
 'being',
 'their',
 'than',
 'thanks',
 'even',
 'get',
 'make',
 'good',
 'had',
 'very',
 'information',
 'does',
 'could',
 'well',
 'want',
 'such',
 'sources',
 'way',
 'name',
 'these',
 'deletion',
 'pages',
 'first',
 'help'

In [20]:
len(vectorizer.get_vocabulary())

200000

In [21]:
vectorized_text = vectorizer(X.values)

In [22]:
vectorized_text

<tf.Tensor: shape=(159571, 1800), dtype=int64, numpy=
array([[  645,    76,     2, ...,     0,     0,     0],
       [    1,    54,  2489, ...,     0,     0,     0],
       [  425,   441,    70, ...,     0,     0,     0],
       ...,
       [32445,  7392,   383, ...,     0,     0,     0],
       [    5,    12,   534, ...,     0,     0,     0],
       [    5,     8,   130, ...,     0,     0,     0]], dtype=int64)>

In [23]:
vectorized_text.shape

TensorShape([159571, 1800])

In [24]:
dataset = tf.data.Dataset.from_tensor_slices((vectorized_text, y))
dataset = dataset.cache()
dataset = dataset.shuffle(160000)
dataset = dataset.batch(16)
dataset = dataset.prefetch(8) # helps prevent bottlenecks

In [25]:
dataset.as_numpy_iterator().next()

(array([[   38,     9,    15, ...,     0,     0,     0],
        [71596,     8,   161, ...,     0,     0,     0],
        [   32,   661,     6, ...,     0,     0,     0],
        ...,
        [  270,  1871,  2332, ...,     0,     0,     0],
        [   23,   140,  3504, ...,     0,     0,     0],
        [    8,  1784,    61, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

In [26]:
batch_X, batch_y = dataset.as_numpy_iterator().next()

In [27]:
batch_X.shape

(16, 1800)

In [28]:
batch_y.shape

(16, 6)

In [29]:
train = dataset.take(int(len(dataset) * 0.7))
val = dataset.skip(int(len(dataset) * 0.7)).take(int(len(dataset) * 0.2))
test = dataset.skip(int(len(dataset) * 0.9)).take(int(len(dataset) * 0.2))

In [30]:
train_generator = train.as_numpy_iterator()

In [31]:
train_generator.next()

(array([[  665,    13,    14, ...,     0,     0,     0],
        [ 1412,  9000,  1613, ...,     0,     0,     0],
        [15720,  6198, 15951, ...,     0,     0,     0],
        ...,
        [   42,     4,     7, ...,     0,     0,     0],
        [  137,  5067, 13190, ...,     0,     0,     0],
        [   77,   196,     3, ...,     0,     0,     0]], dtype=int64),
 array([[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]], dtype=int64))

## Create Sequential Model

In [35]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dropout, Bidirectional, Dense, Embedding

In [41]:
model = Sequential()

# Create the embedding layer
model.add(Embedding(MAX_FEATURES+1, 32))

# Create the bidirectional LSTM
model.add(Bidirectional(LSTM(32, activation='tanh')))

# Feature extractor fully connected layers
model.add(Dense(128, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))

# Final layer
model.add(Dense(6, activation='sigmoid'))

In [42]:
model.compile(loss='binary_crossentropy', optimizer='Adam')


In [43]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 32)          6400032   
                                                                 
 bidirectional_1 (Bidirectio  (None, 64)               16640     
 nal)                                                            
                                                                 
 dense_4 (Dense)             (None, 128)               8320      
                                                                 
 dense_5 (Dense)             (None, 256)               33024     
                                                                 
 dense_6 (Dense)             (None, 128)               32896     
                                                                 
 dense_7 (Dense)             (None, 6)                 774       
                                                      

In [44]:
history = model.fit(train, epochs=1, validation_data=val)

6981/6981 [==============================] - 8998s 1s/step - loss: 0.0629 - val_loss: 0.0460


## Making Predictions

In [45]:
input_text = vectorizer('You freaking suck!')

In [48]:
df.columns[2:]

Index(['toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')

In [47]:
model.predict(np.expand_dims(input_text, axis=0))

1/1 [==============================] - 4s 4s/step


array([[0.99036247, 0.4477122 , 0.9264277 , 0.07055429, 0.8596298 ,
        0.16434565]], dtype=float32)

In [50]:
res = model.predict(np.expand_dims(input_text, axis=0)) # same as: model.predict([input_size])

1/1 [==============================] - 0s 181ms/step


In [57]:
batch_X, batch_y = test.as_numpy_iterator().next()

In [58]:
model.predict(batch_X)

1/1 [==============================] - 0s 219ms/step


array([[9.62602735e-01, 1.68345824e-01, 8.10853899e-01, 3.48891094e-02,
        7.09344804e-01, 9.27737504e-02],
       [1.76528040e-02, 8.73143654e-05, 2.06696941e-03, 7.47953600e-05,
        1.96154858e-03, 1.13006984e-03],
       [1.14218183e-01, 1.35438994e-03, 1.68455299e-02, 1.37763482e-03,
        2.02588327e-02, 9.15121939e-03],
       [1.33165356e-03, 7.21370213e-07, 7.13459740e-05, 5.20575554e-07,
        5.47814961e-05, 3.19858082e-05],
       [9.98276532e-01, 5.16456306e-01, 9.72245753e-01, 4.40417156e-02,
        9.21070039e-01, 1.30176663e-01],
       [2.24029901e-03, 1.88592833e-06, 1.37806594e-04, 1.39842882e-06,
        1.11210422e-04, 6.49310678e-05],
       [4.06815186e-02, 3.23016458e-04, 5.26547059e-03, 2.86651222e-04,
        5.69443777e-03, 3.07452329e-03],
       [8.87835806e-04, 3.07501580e-07, 4.02521437e-05, 2.14256744e-07,
        3.07398113e-05, 1.71820993e-05],
       [6.22473024e-02, 4.84244025e-04, 7.26048835e-03, 4.43116412e-04,
        8.78300983e-03, 

In [59]:
(model.predict(batch_X) > 0.5).astype(int)

1/1 [==============================] - 0s 219ms/step


array([[1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

## Model Evaluation

In [52]:
from tensorflow.keras.metrics import Precision, Recall, CategoricalAccuracy

In [53]:
pre = Precision()
re = Recall()
acc = CategoricalAccuracy()

In [56]:
for batch in test.as_numpy_iterator():
    # Unpack the batch
    X_true, y_true = batch
    
    # Make a prediction
    y_hat = model.predict(X_true)
    
    # Flatten the prediction
    y_true = y_true.flatten()
    y_hat = y_hat.flatten()
    
    pre.update_state(y_true, y_hat)
    re.update_state(y_true, y_hat)
    acc.update_state(y_true, y_hat)

1/1 [==============================] - 0s 196ms/step


1/1 [==============================] - 0s 220ms/step


1/1 [==============================] - 0s 180ms/step


1/1 [==============================] - 0s 180ms/step


1/1 [==============================] - 0s 189ms/step


1/1 [==============================] - 0s 204ms/step


1/1 [==============================] - 0s 156ms/step


In [60]:
print(f'Precision: {pre.result().numpy()}, Recall: {re.result().numpy()}, Accuracy: {acc.result().numpy()}')

Precision: 0.8511074781417847, Recall: 0.6016236543655396, Accuracy: 0.48496994376182556


## Test and Gradio

In [83]:
model = tf.keras.models.load_model('toxicity.h5')

In [84]:
def score_comment(comment):
    vectorized_comment = vectorizer([comment])
    results = model.predict(vectorized_comment)
    
    text = ''
    for idx, col in enumerate(df.columns[2:]):
        text += '{}: {}\n'.format(col, results[0][idx] > 0.5)
        
    return text

In [85]:
interface = gr.Interface(fn=score_comment,
                        inputs=gr.inputs.Textbox(lines=2, placeholder='Comment to score'),
                        outputs='text')

NameError: name 'gr' is not defined

In [76]:
interface.launch(share=True)

NameError: name 'interface' is not defined